### ISSUE TITLE
nginx confs incompatible with wunderkraut/alpine-nginx-pagespeed

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/docker-container-app-configs#3]
When using the Drupal configurations with https://github.com/wunderkraut/alpine-nginx-pagespeed , I get the following errors:

PENDING
FIXED FAILED Upstream https://github.com/wunderkraut/alpine-nginx-pagespeed/commit/c49b95fd36855f81d987f5e04b6ce41cf1ea0c17

```
2016/05/03 10:41:05 [emerg] 1#0: unknown directive "map" in /etc/nginx/nginx.conf:94
nginx: [emerg] unknown directive "map" in /etc/nginx/nginx.conf:94
```

```
./configure: error: invalid option "--with-http_map_module"
```

PENDING

```
2016/05/05 13:54:29 [emerg] 1#0: "keepalive_timeout" directive is duplicate in /etc/nginx/conf.d/nginx_server_ssl.conf:16
nginx: [emerg] "keepalive_timeout" directive is duplicate in /etc/nginx/conf.d/nginx_server_ssl.conf:16
```

**Comment by james-nesbitt** [comment]
Perhaps missing http://nginx.org/en/docs/http/ngx_http_realip_module.html upstream

**Comment by iler** [comment]
I pushed a fix for this here https://github.com/wunderkraut/alpine-nginx-pagespeed/commit/8e020ae699be97348bc3b2675800426c6faa2e48. I thought it was already there but have probably mistakenly deleted it.

**Comment by james-nesbitt** [comment]
```
2016/05/03 10:41:05 [emerg] 1#0: unknown directive "map" in /etc/nginx/nginx.conf:94
nginx: [emerg] unknown directive "map" in /etc/nginx/nginx.conf:94
```

as well?

**Comment by james-nesbitt** [comment]
your patch is totally there.  I am not sure why it didn't build.  I will force that build again.

**Comment by iler** [comment]
That is a different one. This commit fixes that https://github.com/wunderkraut/alpine-nginx-pagespeed/commit/c49b95fd36855f81d987f5e04b6ce41cf1ea0c17

**Comment by james-nesbitt** [comment]
will test now.

**Comment by james-nesbitt** [comment]
```
2016/05/03 10:48:42 [emerg] 1#0: "upstream" directive is not allowed here in /etc/nginx/conf.d/app_drupal.conf:10
nginx: [emerg] "upstream" directive is not allowed here in /etc/nginx/conf.d/app_drupal.conf:10
````

**Comment by iler** [comment]
This commit https://github.com/wunderkraut/docker-container-app-configs/commit/5cc1d8e0c1cc63474be9a1a5666c9091bc991370 fixes the last error about the upstream directive. Obviously was too tired when created these configs...

**Comment by james-nesbitt** [comment]
I've managed to get nginx to run with a subset of the nginx confs.

```
RUN mkdir /etc/nginx/conf.d && \
    wget -O /etc/nginx/nginx.conf https://raw.githubusercontent.com/wunderkraut/docker-container-app-configs/master/nginx/nginx.conf_drupal && \
    wget -O /etc/nginx/conf.d/app_drupal.conf https://raw.githubusercontent.com/wunderkraut/docker-container-app-configs/master/nginx/conf.d/nginx_drupal.conf && \
    wget -P /etc/nginx/conf.d https://raw.githubusercontent.com/wunderkraut/docker-container-app-configs/master/nginx/conf.d/fastcgi_drupal.conf && \
    wget -P /etc/nginx/conf.d https://raw.githubusercontent.com/wunderkraut/docker-container-app-configs/master/nginx/conf.d/nginx_app.conf && \
    wget -P /etc/nginx/conf.d https://raw.githubusercontent.com/wunderkraut/docker-container-app-configs/master/nginx/conf.d/nginx_upstream.conf
```

notice the rename or nginx.conf_drupal->nginx.conf, and nginx_drupal.conf->app_drupal.conf.  Also including the ssl conf gave errors (noted above in the body)

**Comment by iler** [comment]
I renamed the nginx_drupal.conf -> app_drupal.conf. Thanks for noticing this.

**Comment by iler** [comment]
@james-nesbitt duplicate keepalive issue is now solved

**Comment by james-nesbitt** [comment]
no need to string this issue list out.  I will check upstream and run the build again.  Any new problems I'll report separately.
